create table if not exists public.admin_events (
  id bigint generated by default as identity primary key,
  event_date date not null,
  start_time time not null,
  end_time time not null,
  event_type text not null,
  description text not null,
  created_at timestamptz not null default now(),
  constraint admin_events_time_check check (end_time > start_time)
);

alter table public.admin_events enable row level security;

drop policy if exists "Anyone can read admin events" on public.admin_events;
create policy "Anyone can read admin events"
  on public.admin_events
  for select
  to anon, authenticated
  using (true);
