create table if not exists public.group_iv_applications_2026 (
  id bigint generated by default as identity primary key,
  full_name text not null,
  date_of_birth date not null,
  gender text not null,
  permanent_address text not null,
  city text not null,
  pincode text not null,
  email text not null,
  contact_number text not null,
  aadhar_number text not null,
  educational_qualification text not null,
  community text not null check (community in ('SC', 'ST')),
  mother_name text not null,
  mother_occupation text not null,
  father_name text not null,
  father_occupation text not null,
  tnpsc_exams text[] not null default '{}',
  previous_coaching boolean not null default false,
  previous_coaching_year integer,
  interview_status text not null default 'not-held-yet'
    check (interview_status in ('not-held-yet', 'accepted', 'rejected', 'in-review')),
  created_at timestamptz not null default now(),
  constraint group_iv_applications_previous_coaching_year_check check (
    (previous_coaching = true and previous_coaching_year is not null)
    or (previous_coaching = false and previous_coaching_year is null)
  )
);

alter table public.group_iv_applications_2026 enable row level security;

drop policy if exists "Anyone can create Group IV applications 2026" on public.group_iv_applications_2026;
create policy "Anyone can create Group IV applications 2026"
  on public.group_iv_applications_2026
  for insert
  to anon, authenticated
  with check (true);
