create table if not exists public.hall_bookings (
  id bigint generated by default as identity primary key,
  full_name text not null,
  organization text,
  email text not null,
  phone text not null,
  event_date date not null,
  booking_slot text not null check (booking_slot in ('half-morning', 'half-evening', 'full-day')),
  event_type text not null,
  address text not null,
  event_description text not null,
  total_price integer not null check (total_price in (7500, 15000)),
  aadhar_file_path text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  created_at timestamptz not null default now()
);

create unique index if not exists hall_bookings_active_slot_unique
  on public.hall_bookings (event_date, booking_slot)
  where status in ('pending', 'approved');

alter table public.hall_bookings enable row level security;

drop policy if exists "Anyone can create hall bookings" on public.hall_bookings;
create policy "Anyone can create hall bookings"
  on public.hall_bookings
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Anyone can read hall bookings" on public.hall_bookings;
create policy "Anyone can read hall bookings"
  on public.hall_bookings
  for select
  to anon, authenticated
  using (true);

insert into storage.buckets (id, name, public)
values ('booking-documents', 'booking-documents', false)
on conflict (id) do nothing;

drop policy if exists "Anyone can upload booking documents" on storage.objects;
create policy "Anyone can upload booking documents"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'booking-documents');

